Add back in local range resolution
bazelbuild/migration-tooling pull request #50
Opened 2017-08-03 16:03 UTC by kchodorow

If an artifact wants a version and it's resolvable, just use
that version. Don't make an extra round trip to fetch versions
unless the requested version doesn't work out.

Fixes #47.

2017-08-03 18:34 UTC, petroseskinder reviewed
Thanks for tackling the issue. There were three major requests I hammered on in the comments. 

First, if we use this guess based approach, I request that we locally resolve versions for _only pins_. No version ranges. The logic you have now, i.e. looking for an inclusive bound, introduces two different heuristics for selecting version ranges. One where we look for the highest version, and another where you look for an inclusive bound. _I am not a fan of this._  The third comment has a few examples where this is very problematic.

Second, you comment that we are taking 

> an extra round trip to fetch versions unless the requested version doesn't work out.

However, we are currently making only _one_ request per version specification. 

* For each version specification, we request all valid versions in the remote repository. This is our _only_ interaction with aether. 
* Soft pins like "3.0" are treated like unbounded version range e.g. "[3.0, )" 
* From this list of valid versions we select the appropriate one.
     - For soft pins, we simply get the oldest version. If the soft pin is valid, then oldest will be itself. If it doesn't we get the next oldest. This is the protocol we previously agreed upon.
     - For any other version range, we just get the highest version, which we agreed to in the past.

In fact, this change actually introduces additional requests. If our guessed version doesn't exist, then we will make two requests to aether. With the existing approach, we make exactly one request to aether per version specification. 

Third, the issue in #47 was due to version 4.0 not being listed in the [repository metadata](https://repo1.maven.org/maven2/com/google/inject/guice/maven-metadata.xml). That's an issue with the repository, _not us_. Your current solution resolves this specific issue.

However, in the process, it reintroduces a number of other issues mitigated in #45.

2017-08-03 18:34 UTC, petroseskinder commented on generate_workspace/src/main/java/com/google/devtools/build/workspace/maven/Aether.java
> +    if (!result.getExceptions().isEmpty()) {
thank you.

2017-08-03 18:34 UTC, petroseskinder commented on generate_workspace/src/main/java/com/google/devtools/build/workspace/maven/VersionResolver.java
> +      }
**Feedback:** Let's locally resolve versions for _only pins_.

The above logic where you look for an inclusive bound introduces two different heuristics for selecting version ranges. One where we look for the highest version, and another where you look for an inclusive bound. _I am not a fan of this._ 

For illustration, suppose `something:something` has versions {1.0, 2.0, 3.0, 3.5, 4.0, 5.0}.  Let's say we make the following requests:
```
something:something:[3.0,)
something:something:[3.0, 5.5),
something:something:(2.9,)
something:something:[3.0, 5.0],
```

These should all evaluate to version 5.0. However, with the above logic, the first two will evaluate to 3.0, and the last two will evaluate to 5.0. 

**Alternative Option**: If you are adamant about resolving version ranges locally, please remove lines 157-158 with the lower bound, and also add a unit tests for the examples above.

2017-08-03 18:34 UTC, petroseskinder commented on generate_workspace/src/main/java/com/google/devtools/build/workspace/maven/VersionResolver.java
> +    }
**Feedback:** Can you separate out the above lines to a separate function, and remove the org.apache.maven.artifact.versioning classes?

When I was initially reading the code a month or two ago, this portion was very confusing to me. Especially the `getRecommendedVersion` portion, and the versionRange restrictions in 149. 

**Proposed logic for function**: I believe the logic should be 
```java
static String resolveVersionLocally(String versionSpecification) {
    if ( isPin(versionSpecification) ) {
         return getPinnedVersion(versionSpecification);
    }
    return null;
}
```
The comment below argues why I believe we shouldn't locally resolve non-pinned version specs.

**Why remove versioning package**: Supposing you agree to that, it doesn't make sense to introduce the org.apache.maven.artifact.versioning package.

Identifying a pin (hard or soft) is a simple enough task. However, by including this package we add unnecessary mental overhead. For example, why are there multiple restrictions of a VersionRange? what does it mean to be a "restriction"? What is "recommended version" by maven? When is the recommended version invalid? Why is the recommended version invalid for soft pins but not for hard pins or version ranges? 

Previously, I had to dig through the source code and I left with a meh impression of the code quality. All we really need in this context is

```java
private boolean isPin(String versionSpec) {
     return !isVersionRange(versionSpec) || isHardPin(versionSpec);
}
private boolean isHardPin(String versionSpec) {
    if (versionSpec == null) return false;
    int length = versionSpec.length();
    return versionSpec.charAt(0) == '[' && versionSpec.charAt(length -1) == ']'
}
```

Sure we would have to write a few tests. But at least we don't have to inherit maven.versionings overheard and idiosyncratic development schemes.

2017-08-03 19:09 UTC, petroseskinder commented
One additional clarification:

> Don't make an extra round trip to fetch versions unless the requested version doesn't work out.

We are currently making only _one_ request per version specification. 

* For each version specification, we request all valid versions in the remote repository. This is our _only_ interaction with aether. 
* Soft pins like "3.0" are treated like unbounded version range e.g. "[3.0, )" 
* From this list of valid versions we select the appropriate one.
     - For soft pins, we simply get the oldest version. If the soft pin is valid, then oldest will be itself. If it doesn't we get the next oldest. This is the protocol we previously agreed upon.
     - For any other version range, we just get the highest version, which we agreed to in the past.

All in all, the issue in #47 was due to version 4.0 not being listed in the [repository metadata](https://repo1.maven.org/maven2/com/google/inject/guice/maven-metadata.xml). That's an issue with the repository, not us. Your current solution resolves this specific issue, but it's important to acknowledge that this is a hack. We should minimize our reliance on this hack.

2017-08-07 15:06 UTC, petroseskinder requested changes
Just noticed that "request changes" was an option.

2017-08-08 16:17 UTC, petroseskinder commented
@kchodorow bump.

2017-09-08 07:47 UTC, damienmg commented
Abandoning this PR since @kchodorow left the team. Feel free to take over.

2017-09-08 07:47 UTC, closed without merging